<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:include filename="$(find rm_description)/urdf/common/mecanum_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.380"/>
    <xacro:property name="wheel_base" value="0.420"/>
    <xacro:property name="wheel_offset_z" value="-0.1090"/>
    <xacro:property name="wheel_joint_damping" value="1.0"/>
    <xacro:property name="wheel_joint_friction" value="1.0"/>

    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="11.91"/>
                <origin xyz="-0.063 -0.010 -0.027"/>
                <inertia ixx="4.230e-1" ixy="-5.057e-4" ixz="3.328e-2" iyy="3.602e-1"
                         iyz="1.417e-2" izz="5.140e-1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/base.stl" scale="0.001 .001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="-0.043 0 0.020" rpy="0 0 0"/>
                <geometry>
                    <box size="0.486 0.596 0.169"/>
                </geometry>
            </collision>
                        <collision>
                            <origin xyz="-0.130 -0.132 0.255" rpy="0 0 0.8377580"/>
                            <geometry>
                                <box size="0.106 0.186 0.3"/>
                            </geometry>
                        </collision>
                        <collision>
                            <origin xyz="-0.0336 -0.27 0.262" rpy="0 0 -0.7853982"/>
                            <geometry>
                                <box size="0.01 0.033 0.06"/>
                            </geometry>
                        </collision>
            <collision>
                <origin xyz="-0.083 -0.225 0.262" rpy="0 0 -0.7853982"/>
                <geometry>
                    <box size="0.01 0.033 0.06"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.0685 -0.259 0.287" rpy="0 0 0.8377580"/>
                <geometry>
                    <box size="0.003 0.057 0.01"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.0685 -0.259 0.237" rpy="0 0 0.8377580"/>
                <geometry>
                    <box size="0.003 0.057 0.01"/>
                </geometry>
            </collision>

            <collision>
                <origin xyz="-0.0866 0.238 0.2672" rpy="0 0 -0.5061455"/>
                <geometry>
                    <box size="0.08 0.0217 0.3033"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.2041 0.1846 0.25833" rpy="0 0 1.0646508"/>
                <geometry>
                    <box size="0.08 0.0217 0.3033"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.1873 0.0566 0.2672" rpy="0 0 -0.5061455"/>
                <geometry>
                    <box size="0.08 0.0217 0.3033"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.139 0.0847 0.228" rpy="0 0 1.0646508"/>
                <geometry>
                    <box size="0.080 0.003 0.250"/>
                </geometry>
            </collision>
        </link>

        <xacro:mecanum_wheel prefix="left_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="right_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="left_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="right_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>

    </xacro:macro>

</robot>