<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:include filename="$(find rm_description)/urdf/common/mecanum_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.380"/>
    <xacro:property name="wheel_base" value="0.420"/>
    <xacro:property name="wheel_offset_z" value="-0.1090"/>
    <xacro:property name="wheel_joint_damping" value="1.0"/>
    <xacro:property name="wheel_joint_friction" value="1.0"/>

    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="137.6"/>
                <origin xyz="-0.12101 -0.0025 0.25321"/>
                <inertia ixx="1.254e+1" ixy="-8.377e-2" ixz="4.560e+0" iyy=" 1.480e+1"
                         iyz="5.948e-2" izz="4.106e+0"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/base.stl" scale="0.001 .001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.5845 0.526 0.2"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.033 -0.1 0.267" rpy="0 0 0.7853982"/>
                <geometry>
                    <box size="0.0207 0.0207 0.334"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.033 0.10 0.267" rpy="0 0 0.7853982"/>
                <geometry>
                    <box size="0.0207 0.0207 0.334"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.23225 -0.1 0.267" rpy="0 0 0.7853982"/>
                <geometry>
                    <box size="0.0207 0.0207 0.334"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.23225 0.1 0.267" rpy="0 0 0.7853982"/>
                <geometry>
                    <box size="0.0207 0.0207 0.334"/>
                </geometry>
            </collision>
        </link>

        <xacro:mecanum_wheel prefix="front_left" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="front_right" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="back_left" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="back_right" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:wheel_transmission prefix="front_left" mechanical_reduction="1"/>
        <xacro:wheel_transmission prefix="front_right" mechanical_reduction="-1"/>
        <xacro:wheel_transmission prefix="back_left" mechanical_reduction="1"/>
        <xacro:wheel_transmission prefix="back_right" mechanical_reduction="-1"/>

    </xacro:macro>

</robot>