<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rm_description)/urdf/common/swerve_drive.urdf.xacro"/>
    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.4"/>
    <xacro:property name="wheel_base" value="0.4"/>
    <xacro:property name="wheel_offset_z" value="-0.036"/>

    <xacro:macro name="chassis">

        <link name="base_link">
            <inertial>
                <mass value="19.31"/>
                <origin xyz="-0.02282 0.002773 0.008173"/>
                <inertia ixx="4.041e-1" ixy="7.617e-3" ixz="-1.317e-2" iyy="3.322e-1"
                         iyz="7.985e-2" izz="1.8e-1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 .001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>

        <xacro:swerve_drive prefix="left_front" connected_to="base_link"
                            wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_front" connected_to="base_link"
                            wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="left_back" connected_to="base_link"
                            wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_back" connected_to="base_link"
                            wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>

        <xacro:swerve_transmission prefix="left_front" wheel_reduction="13.733" pivot_offset="4.161"/>
        <xacro:swerve_transmission prefix="right_front" wheel_reduction="-13.733" pivot_offset="1.861"/>
        <xacro:swerve_transmission prefix="left_back" wheel_reduction="13.733" pivot_offset="3.656"/>
        <xacro:swerve_transmission prefix="right_back" wheel_reduction="-13.733" pivot_offset="6.283"/>
    </xacro:macro>

</robot>