<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find rm_description)/urdf/common/mecanum_wheel.urdf.xacro"/>

  <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
  <xacro:property name="wheel_track" value="0.500"/>
  <xacro:property name="wheel_base" value="0.475"/>
  <xacro:property name="wheel_offset_z" value="-0.036"/>
  <xacro:property name="wheel_joint_damping" value="1.0"/>
  <xacro:property name="wheel_joint_friction" value="1.0"/>

  <xacro:macro name="chassis" params="roller_type">

    <link name="base_link">
      <inertial>
        <mass value="19.93"/>
        <origin xyz="-0.02282 0.002773 0.008173"/>
        <inertia ixx="5.96e-1" ixy="6.075e-3" ixz="4.655e-2" iyy="9.41e-1"
                 iyz="-3.105e-3" izz="1.381e+0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 .001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <xacro:mecanum_wheel prefix="front_left" connected_to="base_link"
                         wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                         wheel_z_offset="${wheel_offset_z}"
                         reflect="1" roller_type="${roller_type}"/>
    <xacro:mecanum_wheel prefix="front_right" connected_to="base_link"
                         wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                         wheel_z_offset="${wheel_offset_z}"
                         reflect="-1" roller_type="${roller_type}"/>
    <xacro:mecanum_wheel prefix="back_left" connected_to="base_link"
                         wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                         wheel_z_offset="${wheel_offset_z}"
                         reflect="-1" roller_type="${roller_type}"/>
    <xacro:mecanum_wheel prefix="back_right" connected_to="base_link"
                         wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                         wheel_z_offset="${wheel_offset_z}"
                         reflect="1" roller_type="${roller_type}"/>
    <xacro:wheel_transmission prefix="front_left" mechanical_reduction="1"/>
    <xacro:wheel_transmission prefix="front_right" mechanical_reduction="-1"/>
    <xacro:wheel_transmission prefix="back_left" mechanical_reduction="1"/>
    <xacro:wheel_transmission prefix="back_right" mechanical_reduction="-1"/>

  </xacro:macro>

</robot>