rm_base:
  bus:
    - can0
    - can1
    - can2
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  # Configurations of the actuators
  actuators:
    right_front_wheel_motor:
      bus: can0
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 100
    left_front_wheel_motor:
      bus: can0
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 100
    left_back_wheel_motor:
      bus: can0
      id: 0x203
      type: rm_3508
      lp_cutoff_frequency: 100
    right_back_wheel_motor:
      bus: can0
      id: 0x204
      type: rm_3508
      lp_cutoff_frequency: 100
    joint1_motor:
      bus: can2
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 100
    joint2_left_motor:
      bus: can1
      id: 0x002
      type: cheetah
      lp_cutoff_frequency: 100
    joint2_right_motor:
      bus: can1
      id: 0x003
      type: cheetah
      lp_cutoff_frequency: 100
    joint3_motor:
      bus: can1
      id: 0x001
      type: cheetah
      lp_cutoff_frequency: 100
    joint4_motor:
      bus: can2
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 100
    joint5_motor:
      bus: can2
      id: 0x203
      type: rm_3508
      lp_cutoff_frequency: 100
    right_finger_motor:
      bus: can2
      id: 0x204
      type: rm_3508
      lp_cutoff_frequency: 100
    pitch_joint_motor:
      bus: can2
      id: 0x205
      type: rm_3508
      lp_cutoff_frequency: 100
    yaw_joint_motor:
      bus: can2
      id: 0x206
      type: rm_3508
      lp_cutoff_frequency: 100
    mast_joint_motor:
      bus: can2
      id: 0x207
      type: rm_2006
      lp_cutoff_frequency: 100
      need_calibration: true
    stone_platform_joint_motor:
      bus: can0
      id: 0x206
      type: rm_2006
      lp_cutoff_frequency: 100
    card_joint_motor:
      bus: can0
      id: 0x205
      type: rm_2006
      lp_cutoff_frequency: 100



controllers:
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100