rm_base:
  bus:
    - can0
    - can1
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  # Configurations of the actuators
  actuators:
    right_front_wheel_motor:
      bus: can1
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 100
    left_front_wheel_motor:
      bus: can1
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 100
    left_back_wheel_motor:
      bus: can1
      id: 0x203
      type: rm_3508
      lp_cutoff_frequency: 100
    right_back_wheel_motor:
      bus: can1
      id: 0x204
      type: rm_3508
      lp_cutoff_frequency: 100
    joint1_motor:
      bus: can1
      id: 0x205
      type: rm_3508
    joint2_left_motor:
      bus: can0
      id: 0x002
      type: cheetah
    joint2_right_motor:
      bus: can0
      id: 0x003
      type: cheetah
    joint3_motor:
      bus: can0
      id: 0x001
      type: cheetah
    left_wrist_motor:
      bus: can1
      id: 0x206
      type: rm_2006
    right_wrist_motor:
      bus: can1
      id: 0x207
      type: rm_2006
    right_finger_motor:
      bus: can1
      id: 0x208
      type: rm_3508_dir



controllers:
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100