rm_base:
  bus:
    - can0
    - can1
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  # Configurations of the actuators
  actuators:
    drive_joint_motor:
      bus: can0
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 100
    yaw_joint_motor:
      bus: can0
      id: 0x208
      type: rm_6020
      lp_cutoff_frequency: 100
    pitch_joint_motor:
      bus: can1
      id: 0x206
      type: rm_6020
      lp_cutoff_frequency: 100
    left_friction_wheel_joint_motor:
      bus: can1
      id: 0x201
      type: rm_3508_dir
      lp_cutoff_frequency: 100
    right_friction_wheel_joint_motor:
      bus: can1
      id: 0x203
      type: rm_3508_dir
      lp_cutoff_frequency: 100
    trigger_joint_motor:
      bus: can0
      id: 0x203
      type: rm_2006
      lp_cutoff_frequency: 200